# Source :
# https://dev.to/ken_mwaura1/automate-docker-image-builds-and-push-to-github-registry-using-github-actions-4h20
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Checkout SVC
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io

jobs:
  test:
    name: Integration Testing
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Test with Docker
        run: |
          echo ${{ vars.ENV_TEST }} | base64 -d > .env.test
          go test -v ./test/integration/... -count=1

  build-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs:
      - test
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }} # Don't push on PR
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
